import google.generativeai as genai
import json
import datetime
YOUR_API_KEY='API_KEY'

genai.configure(api_key=YOUR_API_KEY)

model=genai.GenerativeModel(model_name='gemini-2.0-flash')

response = model.generate_content(
    "Will you help me build an app?"
)

# print(response.text)







# client = genai.Client(api_key="YOUR_GEMINI_API_KEY")





def extract_date_yesterday():
    """Returns yesterday's date in 'YYYY-MM-DD' format"""
    return (datetime.datetime.now() - datetime.timedelta(days=1)).strftime('%Y-%m-%d')

# print(extract_date_yesterday())

def generate_mongodb_query(natural_query):
    

    prompt = f"""
    You are an expert MongoDB query generator. Convert the following natural language request into a valid MongoDB query.

    Example Natural Query:
    "I have a db named 'Database' and I want only other usernames who were created yesterday from collection 'Person'?"

    Expected Output:
    {{
        "database": "Database",
        "collection": "Person",
        "query": [
            {{
                "$match": {{
                    "Date": "{extract_date_yesterday()}",
                    "username": {{"$ne": "CURRENT_USER"}}
                }}
            }},
            {{
                "$project": {{
                    "username": 1
                }}
            }}
        ]
    }}

    Now convert this request:
    "{natural_query}"

    and remember one thing , the query you give would be directly executed without filtering it so be careful.
    Give query and no other explanation
    """

    # prompt1 =f""" What is the capital of india and how many states are there in India?     """
   
    response = model.generate_content(
    prompt)

    # print(response.text)
    
    return response.text
    
# print(generate_mongodb_query(input("Please enter your query?")))

# def execute_mongodb_query(query_data):
#     """
#     Executes the MongoDB query generated by Gemini.
#     """

#     if not query_data:
#         print("Invalid query data.")
#         return
    
#     # Extract database and collection name
#     db_name = query_data.get("database")
#     collection_name = query_data.get("collection")
#     query_pipeline = query_data.get("query", [])

#     if not db_name or not collection_name or not query_pipeline:
#         print("Missing required database, collection, or query details.")
#         return

#     # Connect to MongoDB database & collection
#     db = client[db_name]
#     collection = db[collection_name]

#     # Execute MongoDB aggregation query
#     results = collection.aggregate(query_pipeline)

#     # Print results
#     for doc in results:
#         print(doc)

# # Example Usage
# user_input = "I have a db named 'Database' and I want only other usernames who were created yesterday from collection 'Person'?"
# mongodb_query = generate_mongodb_query(user_input)
# execute_mongodb_query(mongodb_query)
